apiVersion: apps/v1
kind: Deployment
metadata:
  name: finocplus-deployment
  labels:
    app: finocplus
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: finocplus
  template:
    metadata:
      labels:
        app: finocplus
    spec:
      containers:
      - name: finocplus
        image: saiteja0605/finocplus:latest 
        ports:
        - containerPort: 8080  
        env:
        - name: NODE_ENV
          value: production
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000  
