apiVersion: v1
kind: Service
metadata:
  name: finocplus-service
spec:
  selector:
    app: finocplus
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080  
  type: LoadBalancer  
